In [1]:

import numpy as np

In [2]:
array1=np.array([1,2,3,4])
print(array1)

[1 2 3 4]


In [5]:
array2=np.array([[1,2,3,4],[5,6,7,8]])
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
result=array1+array2
print(result)

[ 6  8 10 12]


In [7]:
array3=np.array([[1,2,3,4],[5,6,7,8]])
result=array3+6
print(result)

[[ 7  8  9 10]
 [11 12 13 14]]


In [8]:
array=np.array([1,2,3,4,5,6])
print(array[1:3])

[2 3]


In [19]:
array5=np.array([1,2,3,4,5,6,7,8,9])
reshaped_array=array5.reshape((3,3))
print(reshaped_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
array=np.array([1,2,3,4,5,6])
print(np.mean(array))
print(np.std(array))

3.5
1.707825127659933


In [21]:
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
result=np.dot(matrix1,matrix2)
print(result)

[[19 22]
 [43 50]]
